# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/node:16.18
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
  linters:
    docker:
      - image: cimg/node:16.18
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
  unit-tests:
    docker:
      - image: cimg/node:16.18
    steps:
      - checkout
      - run: yarn install
      - run: yarn test:unit
  e2e-tests:
    docker:
      - image: cimg/node:16.18
    steps:
      - checkout
      - run: yarn install
workflows:
  test-all:
    jobs:
      - build
      - linters
      - unit-tests
      - e2e-tests
