version: '3.8'
services:
    mysql:
        container_name: ${APP_PREFIX}-mariadb
        image: mariadb:10.6
        restart: on-failure
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            - MYSQL_ROOT_PASSWORD=${APP_PREFIX}
            - MYSQL_USER=${APP_PREFIX}
            - MYSQL_PASSWORD=${APP_PREFIX}
            - MYSQL_DATABASE=${APP_PREFIX}
        volumes:
            - ./data/mysql:/var/lib/mysql:delegated
        ports:
            - ${MYSQL_PORT}:3306
    redis:
        container_name: ${APP_PREFIX}-redis
        image: redis:6.2-alpine
        restart: on-failure
        ports:
            - ${REDIS_PORT}:6379
        command: redis-server --save 20 1 --loglevel warning --requirepass ${APP_PREFIX}
        volumes:
            - ./data/redis:/data:delegated
    mailhog:
        container_name: ${APP_PREFIX}-mailhog
        image: mailhog/mailhog:v1.0.1
        restart: on-failure
        command: ['-storage=maildir', '-maildir-path=/maildir']
        volumes:
            - ./data/mailhog:/maildir:delegated
        ports:
            - ${MAILHOG_UI_PORT}:8025
            - ${MAILHOG_SMTP_PORT}:1025
